export const TAB_BUTTON_SIZE = 40;

export const TAB_INDICATOR_SIZE = 32;

export const TAB_BAR_HORIZONTAL_PADDING = 24;

export const TAB_BAR_HORIZONTAL_MARGIN = 16;

export const TAB_INDICATOR_ANIMATION_DURATION = 300;
