const LOGS = {
  DEFAULT_ERROR_MESSAGE: 'Something went wrong',

  UNKNOWN: 'UNKNOWN',
  ERROR: 'ERROR',
  API_ERROR: 'API_ERROR',

  SIGNIN: 'SIGNIN',
  SIGNUP: 'SIGNUP',
  SIGNOUT: 'SIGNOUT',

  REFRESH_TOKEN: 'REFRESH_TOKEN',

  GET_USER: 'GET_USER',
  SET_USER: 'SET_USER',

  STORAGE_SET: 'STORAGE_SET',
  STORAGE_GET: 'STORAGE_GET',
  STORAGE_REMOVE: 'STORAGE_REMOVE',

  ENCRYPTED_STORAGE_SET: 'ENCRYPTED_STORAGE_SET',
  ENCRYPTED_STORAGE_GET: 'ENCRYPTED_STORAGE_GET',
  ENCRYPTED_STORAGE_REMOVE: 'ENCRYPTED_STORAGE_REMOVE',
};

export default LOGS;
